baseURL = "https://aibyte2.netlify.app/"  
languageCode = "en-us"
title = "ByteBliss"
theme = "PaperMod"

[params]
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowPostNavLinks = true

    [params.homeInfoParams]
    Title = "Unlocking Digital Delights: ByteBliss - Your Gateway to Tech Wonderment!"
    Content = ""



[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1

[[menu.main]]
name = "tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "archives"
url = "/archives/"
weight = 3
